name: 'Marketplace issue automation'
description: 'add issue comments as per response'
author: 'Suhani Chawla'

inputs:
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
  